<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="sina mokhtar">
<meta name="dcterms.date" content="2023-03-07">
<meta name="description" content="[Advanced Data Analysis 2](https://StatAcumen.com/teach/ada12, Stat 428/528, Spring 2023, Prof.&nbsp;Erik Erhardt, UNM">

<title>ADA2: Class 14, Ch 07b, Analysis of Covariance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/quarto-html/quarto.js"></script>
<script src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/quarto-html/popper.min.js"></script>
<script src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/quarto-html/anchor.min.js"></script>
<link href="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ADA2_CL_14_ANCOVA_AbqHomePrices_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ADA2: Class 14, Ch 07b, Analysis of Covariance</h1>
</div>

<div>
  <div class="description">
    <p>[Advanced Data Analysis 2](https://StatAcumen.com/teach/ada12, Stat 428/528, Spring 2023, Prof.&nbsp;Erik Erhardt, UNM</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>sina mokhtar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 7, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>
<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#ancova-model-albuquerque-nm-87108-house-and-apartment-listing-prices" id="toc-ancova-model-albuquerque-nm-87108-house-and-apartment-listing-prices">ANCOVA model: Albuquerque NM 87108, House and Apartment listing prices</a>
  <ul>
  <li><a href="#unusual-assignment-not-top-down-but-up-down-up-down" id="toc-unusual-assignment-not-top-down-but-up-down-up-down">Unusual assignment, not top-down, but up-down-up-down</a>
  <ul>
  <li><a href="#keep-a-record-of-your-decisions" id="toc-keep-a-record-of-your-decisions">Keep a record of your decisions</a></li>
  </ul></li>
  <li><a href="#p-step-1-restrict-data-to-typical-dwellings" id="toc-p-step-1-restrict-data-to-typical-dwellings"><strong>(2 p)</strong> (Step 1) Restrict data to “typical” dwellings</a></li>
  <li><a href="#p-step-3-transform-response-if-necessary." id="toc-p-step-3-transform-response-if-necessary."><strong>(2 p)</strong> (Step 3) Transform response, if necessary.</a>
  <ul>
  <li><a href="#solution" id="toc-solution">Solution</a></li>
  </ul></li>
  <li><a href="#p-step-4-remove-extremely-influential-observations." id="toc-p-step-4-remove-extremely-influential-observations."><strong>(2 p)</strong> (Step 4) Remove extremely influential observations.</a></li>
  <li><a href="#subset-data-for-model-building-and-prediction" id="toc-subset-data-for-model-building-and-prediction">Subset data for model building and prediction</a>
  <ul>
  <li><a href="#solution-1" id="toc-solution-1">Solution</a></li>
  </ul></li>
  <li><a href="#p-step-2-fit-full-two-way-interaction-model." id="toc-p-step-2-fit-full-two-way-interaction-model."><strong>(2 p)</strong> (Step 2) Fit full two-way interaction model.</a>
  <ul>
  <li><a href="#solution-2" id="toc-solution-2">Solution</a></li>
  </ul></li>
  <li><a href="#p-step-5-model-selection-check-model-assumptions." id="toc-p-step-5-model-selection-check-model-assumptions."><strong>(2 p)</strong> (Step 5) Model selection, check model assumptions.</a>
  <ul>
  <li><a href="#solution-3" id="toc-solution-3">Solution</a></li>
  </ul></li>
  <li><a href="#p-step-6-plot-final-model-interpret-coefficients." id="toc-p-step-6-plot-final-model-interpret-coefficients."><strong>(4 p)</strong> (Step 6) Plot final model, interpret coefficients.</a>
  <ul>
  <li><a href="#solution-4" id="toc-solution-4">Solution</a></li>
  </ul></li>
  <li><a href="#p-step-7-transform-predictors." id="toc-p-step-7-transform-predictors."><strong>(2 p)</strong> (Step 7) Transform predictors.</a></li>
  <li><a href="#p-step-8-predict-new-observations-interpret-models-predictive-ability." id="toc-p-step-8-predict-new-observations-interpret-models-predictive-ability."><strong>(4 p)</strong> (Step 8) Predict new observations, interpret model’s predictive ability.</a>
  <ul>
  <li><a href="#solution-5" id="toc-solution-5">Solution</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
<p>This is a challenging dataset, in part because it’s real and messy. I will guide you through a simplified sensible analysis, but other models are possible.</p>
<p><em>Note that I needed to set <code>cache=FALSE</code> to assure all output was updated.</em></p>
<section id="ancova-model-albuquerque-nm-87108-house-and-apartment-listing-prices" class="level1">
<h1>ANCOVA model: Albuquerque NM 87108, House and Apartment listing prices</h1>
<p>Prof Erhardt constructed a dataset of listing prices for dwellings (homes and apartments) for sale from <a href="http://www.zillow.com/homes/for_sale/Albuquerque-NM-87108/95303_rid/any_days/35.095087-106.52167835.035021-106.633258_rect/13_zm/0_mmm/">Zillow.com</a> on Feb 26, 2016 at 1 PM for Albuquerque NM 87108. In this assignment we’ll develop a model to help understand which qualities that contribute to a <strong>typical dwelling’s listing price</strong>. We will then also predict the listing prices of new listings posted on the following day, Feb 27, 2016 by 2 PM.</p>
<p>Because we want to model a <em>typical dwelling</em>, it is completely reasonable to remove “unusual” dwellings from the dataset. Dwellings have a distribution with a <a href="https://en.wikipedia.org/wiki/Long_tail">long tail</a>!</p>
<section id="unusual-assignment-not-top-down-but-up-down-up-down" class="level2">
<h2 class="anchored" data-anchor-id="unusual-assignment-not-top-down-but-up-down-up-down">Unusual assignment, not top-down, but up-down-up-down</h2>
<p>This is an unusual assignment because the workflow of this assignment isn’t top-down; instead, you’ll be scrolling up and down as you make decisions about the data and model you’re fitting. Yes, I have much of the code worked out for you. However, there are data decisions to make early in the code (such as excluding observations, transforming variables, etc.) that depend on the analysis (model checking) later. Think of it as a “choose your own adventure” that I’ve written for you.</p>
<section id="keep-a-record-of-your-decisions" class="level3">
<h3 class="anchored" data-anchor-id="keep-a-record-of-your-decisions">Keep a record of your decisions</h3>
<p>It is always desirable to make your work reproducible, either by someone else or by your future self. For each step you take, keep a diary of (a) what the next minor goal is, (b) what evidence/information you have, (c) what decision you make, and (d) what the outcome was.</p>
<p>For example, here’s the first couple steps of your diary:</p>
<ol type="1">
<li>Include only “typical dwellings”. Based on scatterplot, remove extreme observations. Keep only HOUSE and APARTMENT.</li>
<li>Exclude a few variables to reduce multicollinearity between predictor variables. Exclude <code>Baths</code> and <code>LotSize</code>.</li>
<li>etc.</li>
</ol>
</section>
</section>
<section id="p-step-1-restrict-data-to-typical-dwellings" class="level2">
<h2 class="anchored" data-anchor-id="p-step-1-restrict-data-to-typical-dwellings"><strong>(2 p)</strong> (Step 1) Restrict data to “typical” dwellings</h2>
<p><strong>Step 1:</strong> After looking at the scatterplot below, identify what you consider to be a “typical dwelling” and exclude observations far from that range. For example, there are only a couple <code>TypeSale</code> that are common enough to model; remember to run <code>factor()</code> again to remove factor levels that no longer appear.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(erikmisc)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── erikmisc 0.1.18 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ tibble 3.1.7      ✔ dplyr  1.0.10</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ─────────────────────────────────────────── erikmisc_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>erikmisc, solving common complex data analysis workflows
  by Dr. Erik Barry Erhardt &lt;erik@StatAcumen.com&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages
───────────────────────────────────────
tidyverse 1.3.2 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ ggplot2 3.4.0     ✔ purrr   1.0.1
✔ tidyr   1.2.1     ✔ stringr 1.5.0
✔ readr   2.1.2     ✔ forcats 0.5.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># First, download the data to your computer,</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   save in the same folder as this Rmd file.</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># read the data, skip the first two comment lines of the data file</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>dat_abq <span class="ot">&lt;-</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>(<span class="st">"ADA2_CL_14_HomePricesZillow_Abq87108.csv"</span>, <span class="at">skip=</span><span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">n</span>()</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  , <span class="at">TypeSale =</span> <span class="fu">factor</span>(TypeSale)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># To help scale the intercept to a more reasonable value</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="co">#   Scaling the x-variables are sometimes done to the mean of each x.</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># center year at 1900 (negative values are older, -10 is built in 1890)</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  , <span class="at">YearBuilt_1900 =</span> YearBuilt <span class="sc">-</span> <span class="dv">1900</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    id, <span class="fu">everything</span>()</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    , <span class="sc">-</span>Address, <span class="sc">-</span>YearBuilt</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 143 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Address, TypeSale
dbl (7): PriceList, Beds, Baths, Size_sqft, LotSize, YearBuilt, DaysListed

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat_abq)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
     id TypeSale  PriceList  Beds Baths Size_sqft LotSize DaysListed
  &lt;int&gt; &lt;fct&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
1     1 HOUSE        186900     3     2      1305    6969          0
2     2 APARTMENT    305000     1     1      2523    6098          0
3     3 APARTMENT    244000     1     1      2816    6098          0
4     4 CONDO        108000     3     2      1137      NA          0
5     5 CONDO         64900     2     1      1000      NA          1
6     6 HOUSE        275000     3     3      2022    6098          1
# … with 1 more variable: YearBuilt_1900 &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## RETURN HERE TO SUBSET THE DATA</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>dat_abq <span class="ot">&lt;-</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  dat_abq <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    TypeSale <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"APARTMENT"</span> , <span class="st">"HOUSE"</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="co">#, !id %in% c(120, 130, 50)# (X &lt;= z)  # keep observations where variable X &lt;= value z</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">TypeSale =</span> <span class="fu">factor</span>(TypeSale)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co"># note, if you remove a level from a categorical variable, then run factor() again</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># SOLUTION</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># these deletions are based only on the scatter plot in order to have</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#  "typical" dwellings</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat_abq)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id              TypeSale    PriceList            Beds      
 Min.   :  1.00   APARTMENT:37   Min.   :  65000   Min.   :1.000  
 1st Qu.: 40.50   HOUSE    :74   1st Qu.: 144450   1st Qu.:1.000  
 Median : 71.00                  Median : 175000   Median :3.000  
 Mean   : 74.59                  Mean   : 236288   Mean   :2.261  
 3rd Qu.:112.00                  3rd Qu.: 257450   3rd Qu.:3.000  
 Max.   :143.00                  Max.   :3110000   Max.   :5.000  
     Baths         Size_sqft        LotSize         DaysListed    
 Min.   :1.000   Min.   :  783   Min.   :  3049   Min.   :   0.0  
 1st Qu.:1.000   1st Qu.: 1360   1st Qu.:  6534   1st Qu.:  34.5  
 Median :1.000   Median : 1780   Median :  6969   Median :  86.0  
 Mean   :1.563   Mean   : 2398   Mean   : 13746   Mean   : 129.2  
 3rd Qu.:2.000   3rd Qu.: 2640   3rd Qu.:  8712   3rd Qu.: 187.5  
 Max.   :5.000   Max.   :33000   Max.   :609840   Max.   :1867.0  
 YearBuilt_1900  
 Min.   : 30.00  
 1st Qu.: 50.00  
 Median : 52.00  
 Mean   : 56.46  
 3rd Qu.: 60.00  
 Max.   :106.00  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#filter(dat_abq, id == 21)</span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ggpairs(dat_abq[,c("TypeSale", "PriceList", "Beds", "Baths", "Size_sqft")])</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(dat_abq[,<span class="fu">c</span>(<span class="st">"TypeSale"</span>, <span class="st">"PriceList"</span>, <span class="st">"Beds"</span>, <span class="st">"Baths"</span>, <span class="st">"Size_sqft"</span>, <span class="st">"LotSize"</span>, <span class="st">"DaysListed"</span>, <span class="st">"YearBuilt_1900"</span>)], <span class="at">mapping =</span> ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">color=</span>TypeSale, <span class="at">alpha=</span>.<span class="dv">5</span>))</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor(x, y): the standard deviation is zero

Warning in cor(x, y): the standard deviation is zero</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor(x, y): the standard deviation is zero

Warning in cor(x, y): the standard deviation is zero

Warning in cor(x, y): the standard deviation is zero

Warning in cor(x, y): the standard deviation is zero

Warning in cor(x, y): the standard deviation is zero</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor(x, y): the standard deviation is zero

Warning in cor(x, y): the standard deviation is zero

Warning in cor(x, y): the standard deviation is zero

Warning in cor(x, y): the standard deviation is zero</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat_abq,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>Size_sqft,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y=</span>PriceList,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">color=</span>TypeSale,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">label=</span>id))<span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">alpha =</span> .<span class="dv">5</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">nudge_x =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="576"></p>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>dat_abq <span class="ot">&lt;-</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  dat_abq <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>     <span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">120</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat_abq,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>Size_sqft,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">y=</span>PriceList,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">color=</span>TypeSale,</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">label=</span>id))<span class="sc">+</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">alpha =</span> .<span class="dv">5</span>,</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">nudge_x =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="576"></p>
</div>
</div>
</section>
<section id="p-step-3-transform-response-if-necessary." class="level2">
<h2 class="anchored" data-anchor-id="p-step-3-transform-response-if-necessary."><strong>(2 p)</strong> (Step 3) Transform response, if necessary.</h2>
<p><strong>Step 3:</strong> Does the response variable require a transformation? If so, what transformation is recommended from the model diagnostic plots (Box-Cox)?</p>
<section id="solution" class="level3">
<h3 class="anchored" data-anchor-id="solution">Solution</h3>
<p>[answer]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>full.model.lm <span class="ot">=</span> <span class="fu">lm</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  PriceList <span class="sc">~</span> (TypeSale <span class="sc">+</span> Beds <span class="sc">+</span> Baths <span class="sc">+</span> Size_sqft <span class="sc">+</span> LotSize <span class="sc">+</span> DaysListed <span class="sc">+</span> YearBuilt_1900)<span class="sc">^</span><span class="dv">2</span>, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat_abq)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full.model.lm)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PriceList ~ (TypeSale + Beds + Baths + Size_sqft + 
    LotSize + DaysListed + YearBuilt_1900)^2, data = dat_abq)

Residuals:
    Min      1Q  Median      3Q     Max 
-138003  -34733     -74   26506  120068 

Coefficients: (2 not defined because of singularities)
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   7.515e+04  1.689e+05   0.445  0.65756    
TypeSaleHOUSE                 7.072e+05  2.429e+05   2.912  0.00461 ** 
Beds                         -8.792e+04  9.482e+04  -0.927  0.35648    
Baths                        -9.145e+04  1.096e+05  -0.834  0.40661    
Size_sqft                     9.889e+01  7.656e+01   1.292  0.20007    
LotSize                       5.270e+00  2.326e+01   0.227  0.82130    
DaysListed                   -8.780e+01  3.932e+02  -0.223  0.82388    
YearBuilt_1900               -4.601e+03  2.973e+03  -1.548  0.12548    
TypeSaleHOUSE:Beds                   NA         NA      NA       NA    
TypeSaleHOUSE:Baths                  NA         NA      NA       NA    
TypeSaleHOUSE:Size_sqft      -6.200e+01  5.623e+01  -1.103  0.27342    
TypeSaleHOUSE:LotSize        -1.993e+01  2.712e+01  -0.735  0.46447    
TypeSaleHOUSE:DaysListed     -5.745e+01  2.769e+02  -0.207  0.83618    
TypeSaleHOUSE:YearBuilt_1900 -8.792e+03  5.191e+03  -1.694  0.09406 .  
Beds:Baths                   -4.642e+04  3.725e+04  -1.246  0.21619    
Beds:Size_sqft                5.319e+01  2.034e+01   2.615  0.01059 *  
Beds:LotSize                  8.419e+00  7.826e+00   1.076  0.28512    
Beds:DaysListed               1.833e+01  1.410e+02   0.130  0.89686    
Beds:YearBuilt_1900           7.958e+00  1.919e+03   0.004  0.99670    
Baths:Size_sqft               3.062e+00  2.636e+01   0.116  0.90782    
Baths:LotSize                -8.764e+00  6.685e+00  -1.311  0.19345    
Baths:DaysListed              7.879e+01  1.932e+02   0.408  0.68443    
Baths:YearBuilt_1900          5.838e+03  1.308e+03   4.465 2.51e-05 ***
Size_sqft:LotSize            -2.270e-04  4.627e-03  -0.049  0.96098    
Size_sqft:DaysListed         -1.279e-01  1.402e-01  -0.912  0.36434    
Size_sqft:YearBuilt_1900     -1.776e+00  1.385e+00  -1.282  0.20344    
LotSize:DaysListed           -2.248e-02  2.948e-02  -0.762  0.44793    
LotSize:YearBuilt_1900        2.750e-01  3.330e-01   0.826  0.41133    
DaysListed:YearBuilt_1900     5.472e+00  4.979e+00   1.099  0.27494    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 58820 on 83 degrees of freedom
Multiple R-squared:  0.7732,    Adjusted R-squared:  0.7021 
F-statistic: 10.88 on 26 and 83 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#cor(dat_abq[, c("PriceList" , "Beds" ,  "Baths" , "Size_sqft" , "LotSize" , "DaysListed" , "YearBuilt_1900")])</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co">#car::Anova(full.model.lm, type=3)</span></span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(full.model.lm)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-5-4.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 6.404039, Df = 1, p = 0.011386</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-error">
<pre><code>Error in vif.default(fit): there are aliased coefficients in the model</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-5-5.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>based on coxbox plot we do log transformation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>full.model.log <span class="ot">=</span> <span class="fu">lm</span>(</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(PriceList) <span class="sc">~</span> (TypeSale <span class="sc">+</span> Beds <span class="sc">+</span> Baths <span class="sc">+</span> Size_sqft <span class="sc">+</span> LotSize <span class="sc">+</span> DaysListed <span class="sc">+</span> YearBuilt_1900)<span class="sc">^</span><span class="dv">2</span>, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat_abq)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full.model.lm)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PriceList ~ (TypeSale + Beds + Baths + Size_sqft + 
    LotSize + DaysListed + YearBuilt_1900)^2, data = dat_abq)

Residuals:
    Min      1Q  Median      3Q     Max 
-138003  -34733     -74   26506  120068 

Coefficients: (2 not defined because of singularities)
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   7.515e+04  1.689e+05   0.445  0.65756    
TypeSaleHOUSE                 7.072e+05  2.429e+05   2.912  0.00461 ** 
Beds                         -8.792e+04  9.482e+04  -0.927  0.35648    
Baths                        -9.145e+04  1.096e+05  -0.834  0.40661    
Size_sqft                     9.889e+01  7.656e+01   1.292  0.20007    
LotSize                       5.270e+00  2.326e+01   0.227  0.82130    
DaysListed                   -8.780e+01  3.932e+02  -0.223  0.82388    
YearBuilt_1900               -4.601e+03  2.973e+03  -1.548  0.12548    
TypeSaleHOUSE:Beds                   NA         NA      NA       NA    
TypeSaleHOUSE:Baths                  NA         NA      NA       NA    
TypeSaleHOUSE:Size_sqft      -6.200e+01  5.623e+01  -1.103  0.27342    
TypeSaleHOUSE:LotSize        -1.993e+01  2.712e+01  -0.735  0.46447    
TypeSaleHOUSE:DaysListed     -5.745e+01  2.769e+02  -0.207  0.83618    
TypeSaleHOUSE:YearBuilt_1900 -8.792e+03  5.191e+03  -1.694  0.09406 .  
Beds:Baths                   -4.642e+04  3.725e+04  -1.246  0.21619    
Beds:Size_sqft                5.319e+01  2.034e+01   2.615  0.01059 *  
Beds:LotSize                  8.419e+00  7.826e+00   1.076  0.28512    
Beds:DaysListed               1.833e+01  1.410e+02   0.130  0.89686    
Beds:YearBuilt_1900           7.958e+00  1.919e+03   0.004  0.99670    
Baths:Size_sqft               3.062e+00  2.636e+01   0.116  0.90782    
Baths:LotSize                -8.764e+00  6.685e+00  -1.311  0.19345    
Baths:DaysListed              7.879e+01  1.932e+02   0.408  0.68443    
Baths:YearBuilt_1900          5.838e+03  1.308e+03   4.465 2.51e-05 ***
Size_sqft:LotSize            -2.270e-04  4.627e-03  -0.049  0.96098    
Size_sqft:DaysListed         -1.279e-01  1.402e-01  -0.912  0.36434    
Size_sqft:YearBuilt_1900     -1.776e+00  1.385e+00  -1.282  0.20344    
LotSize:DaysListed           -2.248e-02  2.948e-02  -0.762  0.44793    
LotSize:YearBuilt_1900        2.750e-01  3.330e-01   0.826  0.41133    
DaysListed:YearBuilt_1900     5.472e+00  4.979e+00   1.099  0.27494    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 58820 on 83 degrees of freedom
Multiple R-squared:  0.7732,    Adjusted R-squared:  0.7021 
F-statistic: 10.88 on 26 and 83 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(full.model.log)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.5741436, Df = 1, p = 0.44862</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-error">
<pre><code>Error in vif.default(fit): there are aliased coefficients in the model</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid" width="480"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>dat_abq[<span class="dv">21</span>,]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 9
     id TypeSale PriceList  Beds Baths Size_sqft LotSize DaysListed
  &lt;int&gt; &lt;fct&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
1    31 HOUSE       175000     3     3      2314  609840         22
# … with 1 more variable: YearBuilt_1900 &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>dat_abq <span class="ot">&lt;-</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  dat_abq <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Price in units of $1000</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">PriceListK =</span> PriceList <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># SOLUTION</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>PriceList</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat_abq)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [110 × 9] (S3: tbl_df/tbl/data.frame)
 $ id            : int [1:110] 1 2 3 6 7 9 10 12 13 14 ...
 $ TypeSale      : Factor w/ 2 levels "APARTMENT","HOUSE": 2 1 1 2 2 2 2 1 2 2 ...
 $ Beds          : num [1:110] 3 1 1 3 2 3 3 1 4 2 ...
 $ Baths         : num [1:110] 2 1 1 3 1 2 2 1 2 1 ...
 $ Size_sqft     : num [1:110] 1305 2523 2816 2022 1440 ...
 $ LotSize       : num [1:110] 6969 6098 6098 6098 8712 ...
 $ DaysListed    : num [1:110] 0 0 0 1 1 1 2 2 6 6 ...
 $ YearBuilt_1900: num [1:110] 54 48 89 52 52 58 52 49 41 53 ...
 $ PriceListK    : num [1:110] 187 305 244 275 133 ...
 - attr(*, "na.action")= 'omit' Named int [1:21] 12 18 20 21 23 29 37 38 57 67 ...
  ..- attr(*, "names")= chr [1:21] "12" "18" "20" "21" ...</code></pre>
</div>
</div>
</section>
</section>
<section id="p-step-4-remove-extremely-influential-observations." class="level2">
<h2 class="anchored" data-anchor-id="p-step-4-remove-extremely-influential-observations."><strong>(2 p)</strong> (Step 4) Remove extremely influential observations.</h2>
<p><strong>Step 4:</strong> The goal is to develop a model that will work well for the typical dwellings. If an observation is highly influential, then it’s unusual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Remove influential observation</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  dat_abq <span class="ot">&lt;-</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>    dat_abq <span class="sc">%&gt;%</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span>   <span class="co"># !(id  %in% c( ... ))</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># SOLUTION</span></span></code></pre></div>
</div>
</section>
<section id="subset-data-for-model-building-and-prediction" class="level2">
<h2 class="anchored" data-anchor-id="subset-data-for-model-building-and-prediction">Subset data for model building and prediction</h2>
<p>Create a subset of the data for building the model, and another subset for prediction later on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove observations with NAs</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>dat_abq <span class="ot">&lt;-</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  dat_abq <span class="sc">%&gt;%</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="co"># the data subset we will use to build our model</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>dat_sub <span class="ot">&lt;-</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  dat_abq <span class="sc">%&gt;%</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>    DaysListed <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a><span class="co"># the data subset we will predict from our model</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>dat_pred <span class="ot">&lt;-</span></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>  dat_abq <span class="sc">%&gt;%</span></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>    DaysListed <span class="sc">==</span> <span class="dv">0</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># the prices we hope to predict closely from our model</span></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">PriceListK_true =</span> PriceListK</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># set them to NA to predict them later</span></span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>  , <span class="at">PriceListK =</span> <span class="cn">NA</span></span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<p>Scatterplot of the model-building subset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">, this plot takes a long time if you're repeadly recompiling the document.</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># comment the "print(p)" line so save some time when you're not evaluating this plot.</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggpairs</span>(</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    dat_sub</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  , <span class="at">mapping =</span> ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">colour =</span> TypeSale, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  , <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="st">"points"</span>)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  , <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="st">"cor"</span>)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  , <span class="at">progress =</span> <span class="cn">FALSE</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="co">#print(p)</span></span></code></pre></div>
</div>
<p>There are clearly some unusual observations. Go back to the first code chunk and remove some observations that don’t represent a “typical” dwelling.</p>
<p>For example, remove these dwellings (in code above):</p>
<ul>
<li>Super expensive dwelling</li>
<li>Dwellings with huge lots</li>
<li>Dwellings that were listed for years</li>
<li>Because most dwellings were APARTMENTs and HOUSEs, remove the others (there are only 1 or so of each).</li>
</ul>
<p>Discuss the observed correlations or other outstanding features in the data.</p>
<section id="solution-1" class="level3">
<h3 class="anchored" data-anchor-id="solution-1">Solution</h3>
<p>[answer]</p>
<p>Features of data:</p>
</section>
</section>
<section id="p-step-2-fit-full-two-way-interaction-model." class="level2">
<h2 class="anchored" data-anchor-id="p-step-2-fit-full-two-way-interaction-model."><strong>(2 p)</strong> (Step 2) Fit full two-way interaction model.</h2>
<p><em>You’ll revisit this section after each modification of the data above.</em></p>
<p><strong>Step 2:</strong> Let’s fit the full two-way interaction model and assess the assumptions. However, some of the predictor variables are highly correlated. Recall that the interpretation of a beta coefficient is “the expected increase in the response for a 1-unit increase in <span class="math inline">\(x\)</span> with all other predictors held constant”. It’s hard to hold one variable constant if it’s correlated with another variable you’re increasing. Therefore, we’ll make a decision to retain some variables but not others depending on their correlation values. (In the PCA chapter, we’ll see another strategy.)</p>
<p>Somewhat arbitrarily, let’s exclude <code>Baths</code> (since highly correlated with <code>Beds</code> and <code>Size_sqft</code>). Let’s also exclude <code>LotSize</code> (since highly correlated with <code>Size_sqft</code>). Modify the code below. Notice that because APARTMENTs don’t have more than 1 Beds or Baths, those interaction terms need to be excluded from the model; I show you how to do this manually using the <code>update()</code> function.</p>
<p>Note that the formula below <code>y ~ (x1 + x2 + x3)^2</code> expands into all main effects and two-way interactions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">## SOLUTION</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  lm_full <span class="ot">&lt;-</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lm</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>      PriceListK <span class="sc">~</span> (TypeSale <span class="sc">+</span> Beds <span class="sc">+</span> Size_sqft <span class="sc">+</span> DaysListed <span class="sc">+</span> YearBuilt_1900)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    , <span class="at">data =</span> dat_sub</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#lm_full &lt;-</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#  lm(</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    PriceListK ~ (Beds + Baths + Size_sqft + LotSize + DaysListed + YearBuilt_1900)^2</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#  , data = dat_sub</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="co">#  )</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>  lm_full</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PriceListK ~ (TypeSale + Beds + Size_sqft + DaysListed + 
    YearBuilt_1900)^2, data = dat_sub)

Coefficients:
                 (Intercept)                 TypeSaleHOUSE  
                   6.238e+01                     2.325e+02  
                        Beds                     Size_sqft  
                  -1.235e+02                     9.385e-02  
                  DaysListed                YearBuilt_1900  
                   1.425e-03                     1.412e-01  
          TypeSaleHOUSE:Beds       TypeSaleHOUSE:Size_sqft  
                          NA                     5.541e-02  
    TypeSaleHOUSE:DaysListed  TypeSaleHOUSE:YearBuilt_1900  
                   4.783e-02                    -4.574e+00  
              Beds:Size_sqft               Beds:DaysListed  
                   4.005e-03                    -3.416e-02  
         Beds:YearBuilt_1900          Size_sqft:DaysListed  
                   2.077e+00                     6.765e-05  
    Size_sqft:YearBuilt_1900     DaysListed:YearBuilt_1900  
                  -9.163e-04                    -1.885e-03  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(car)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">try</span>(<span class="fu">Anova</span>(lm_full, <span class="at">type=</span><span class="dv">3</span>))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Error in Anova.III.lm(mod, error, singular.ok = singular.ok, ...) : 
  there are aliased coefficients in the model</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Note that this doesn't work because APARTMENTs only have 1 bed and 1 bath.</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="do">## There isn't a second level of bed or bath to estimate the interaction.</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Therefore, remove those two terms</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  lm_full <span class="ot">&lt;-</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">update</span>(</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>      lm_full</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>    , . <span class="sc">~</span> . <span class="sc">-</span> TypeSale<span class="sc">:</span>Beds</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(car)</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">try</span>(<span class="fu">Anova</span>(lm_full, <span class="at">type=</span><span class="dv">3</span>))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: PriceListK
                          Sum Sq Df F value Pr(&gt;F)
(Intercept)                  650  1  0.1196 0.7302
TypeSale                    5242  1  0.9648 0.3285
Beds                        8430  1  1.5516 0.2161
Size_sqft                   7333  1  1.3498 0.2483
DaysListed                     0  1  0.0000 0.9974
YearBuilt_1900                13  1  0.0024 0.9609
TypeSale:Size_sqft          9737  1  1.7922 0.1840
TypeSale:DaysListed          160  1  0.0294 0.8642
TypeSale:YearBuilt_1900     6812  1  1.2539 0.2657
Beds:Size_sqft               706  1  0.1300 0.7193
Beds:DaysListed              470  1  0.0865 0.7694
Beds:YearBuilt_1900         7886  1  1.4516 0.2314
Size_sqft:DaysListed        1509  1  0.2777 0.5995
Size_sqft:YearBuilt_1900    3853  1  0.7091 0.4019
DaysListed:YearBuilt_1900    557  1  0.1026 0.7495
Residuals                 499825 92               </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Uncomment this line when you're ready to assess the model assumptions</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="co">#e_plot_lm_diagostics(lm_full)</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="co"># List the row numbers with id numbers</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   The row numbers appear in the residual plots.</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="co">#   The id number can be used to exclude values in code above.</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>dat_sub <span class="sc">%&gt;%</span> <span class="fu">select</span>(id) <span class="sc">%&gt;%</span> <span class="fu">print</span>(<span class="at">n =</span> <span class="cn">Inf</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 107 × 1
       id
    &lt;int&gt;
  1     6
  2     7
  3     9
  4    10
  5    12
  6    13
  7    14
  8    15
  9    17
 10    19
 11    20
 12    21
 13    22
 14    24
 15    27
 16    29
 17    30
 18    31
 19    32
 20    33
 21    35
 22    36
 23    38
 24    39
 25    40
 26    41
 27    42
 28    45
 29    46
 30    47
 31    48
 32    49
 33    50
 34    51
 35    52
 36    53
 37    54
 38    55
 39    56
 40    57
 41    58
 42    59
 43    60
 44    61
 45    62
 46    64
 47    65
 48    66
 49    67
 50    68
 51    69
 52    70
 53    71
 54    72
 55    77
 56    78
 57    79
 58    80
 59    81
 60    83
 61    84
 62    85
 63    86
 64    87
 65    91
 66    92
 67    94
 68    95
 69    99
 70   100
 71   101
 72   102
 73   103
 74   104
 75   105
 76   106
 77   108
 78   109
 79   110
 80   111
 81   113
 82   114
 83   115
 84   116
 85   117
 86   119
 87   121
 88   122
 89   123
 90   124
 91   126
 92   127
 93   128
 94   129
 95   130
 96   131
 97   132
 98   133
 99   134
100   135
101   136
102   137
103   138
104   140
105   141
106   142
107   143</code></pre>
</div>
</div>
<p>After Step 2, interpret the residual plots. What are the primary issues in the original model?</p>
<section id="solution-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-2">Solution</h3>
<p>[answer]</p>
</section>
</section>
<section id="p-step-5-model-selection-check-model-assumptions." class="level2">
<h2 class="anchored" data-anchor-id="p-step-5-model-selection-check-model-assumptions."><strong>(2 p)</strong> (Step 5) Model selection, check model assumptions.</h2>
<p>Using <code>step(..., direction="both")</code> with the BIC criterion, perform model selection.</p>
<section id="solution-3" class="level3">
<h3 class="anchored" data-anchor-id="solution-3">Solution</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="do">## BIC</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="co"># option: test="F" includes additional information</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="co">#           for parameter estimate tests that we're familiar with</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co"># option: for BIC, include k=log(nrow( [data.frame name] ))</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>lm_red_BIC <span class="ot">&lt;-</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step</span>(</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>    lm_full</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  , <span class="at">direction =</span> <span class="st">"both"</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>  , <span class="at">test =</span> <span class="st">"F"</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>  , <span class="at">trace =</span> <span class="dv">0</span></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>  , <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(dat_sub))</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>lm_final <span class="ot">&lt;-</span> lm_red_BIC</span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Uncomment this line when you're ready to assess the model assumptions</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co">#e_plot_lm_diagostics(lm_final)</span></span></code></pre></div>
</div>
<p>Model assumptions appear to be reasonably met. A few influential observations exist.</p>
</section>
</section>
<section id="p-step-6-plot-final-model-interpret-coefficients." class="level2">
<h2 class="anchored" data-anchor-id="p-step-6-plot-final-model-interpret-coefficients."><strong>(4 p)</strong> (Step 6) Plot final model, interpret coefficients.</h2>
<p>If you arrived at the same model I did, then the code below will plot it. Eventually (after Step 7), the fitted model equations will describe the each dwelling <code>TypeSale</code> and interpret the coefficients.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_14_ANCOVA_AbqHomePrices_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Anova(lm_final, type=3)</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_final)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PriceListK ~ TypeSale + Size_sqft + TypeSale:Size_sqft, 
    data = dat_sub)

Residuals:
    Min      1Q  Median      3Q     Max 
-179.64  -38.39   -4.00   26.56  394.90 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              63.46842   28.35874   2.238   0.0274 *  
TypeSaleHOUSE           -54.32481   35.25025  -1.541   0.1264    
Size_sqft                 0.04430    0.00873   5.075 1.73e-06 ***
TypeSaleHOUSE:Size_sqft   0.07505    0.01409   5.328 5.86e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 71.18 on 103 degrees of freedom
Multiple R-squared:  0.5843,    Adjusted R-squared:  0.5722 
F-statistic: 48.27 on 3 and 103 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Fitted model equation is <span class="math display">\[
  \widehat{\log_{10}(\textrm{PriceList})}
    =
    63.5
  + -54.3 I(\textrm{TypeSale} = \textrm{HOUSE})
  + 0.0443 \log_{10}(\textrm{Size_sqft})
\]</span></p>
<section id="solution-4" class="level3">
<h3 class="anchored" data-anchor-id="solution-4">Solution</h3>
<p>After Step 7, return and intepret the model coefficients above.</p>
<p>[answer]</p>
</section>
</section>
<section id="p-step-7-transform-predictors." class="level2">
<h2 class="anchored" data-anchor-id="p-step-7-transform-predictors."><strong>(2 p)</strong> (Step 7) Transform predictors.</h2>
<p>We now have enough information to see that a transformation of a predictor can be useful. See the curvature with <code>Size_sqft</code>? This is one of the headaches of regression modelling, <em>everything depends on everything else</em> and you learn as you go. Return to the top and transform <code>Size_sqft</code> and <code>LotSize</code>.</p>
<p>A nice feature of this transformation is that the model interaction goes away. Our interpretation is now on the log scale, but it’s a simpler model.</p>
</section>
<section id="p-step-8-predict-new-observations-interpret-models-predictive-ability." class="level2">
<h2 class="anchored" data-anchor-id="p-step-8-predict-new-observations-interpret-models-predictive-ability."><strong>(4 p)</strong> (Step 8) Predict new observations, interpret model’s predictive ability.</h2>
<p>Using the <code>predict()</code> function, we’ll input the data we held out to predict earlier, and use our final model to predict the <code>PriceListK</code> response. Note that <code>10^lm_pred</code> is the table of values on the scale of “thousands of dollars”.</p>
<p>Interpret the predictions below the output.</p>
<p>How well do you expect this model to predict? Justify your answer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predict new observations, convert to data frame</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>lm_pred <span class="ot">&lt;-</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">predict</span>(</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>      lm_final</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    , <span class="at">newdata =</span> dat_pred</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    , <span class="at">interval =</span> <span class="st">"prediction"</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># add column of actual list prices</span></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">PriceListK =</span> dat_pred<span class="sc">$</span>PriceListK_true</span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>lm_pred</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr PriceListK
1 164.9003 22.45417 307.3464      186.9
2 175.2411 31.83890 318.6434      305.0
3 188.2215 44.98014 331.4628      244.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># on "thousands of dollars" scale</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span><span class="sc">^</span>lm_pred</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            fit          lwr           upr    PriceListK
1 7.948807e+164 2.845553e+22 2.220431e+307 7.943282e+186
2 1.742377e+175 6.900798e+31           Inf 1.000000e+305
3 1.665275e+188 9.552907e+44           Inf 1.000000e+244</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># attributes of the three predicted observations</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>dat_pred <span class="sc">%&gt;%</span> <span class="fu">print</span>(<span class="at">n =</span> <span class="cn">Inf</span>, <span class="at">width =</span> <span class="cn">Inf</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 10
     id TypeSale   Beds Baths Size_sqft LotSize DaysListed YearBuilt_1900
  &lt;int&gt; &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;
1     1 HOUSE         3     2      1305    6969          0             54
2     2 APARTMENT     1     1      2523    6098          0             48
3     3 APARTMENT     1     1      2816    6098          0             89
  PriceListK PriceListK_true
  &lt;lgl&gt;                &lt;dbl&gt;
1 NA                    187.
2 NA                    305 
3 NA                    244 </code></pre>
</div>
</div>
<section id="solution-5" class="level3">
<h3 class="anchored" data-anchor-id="solution-5">Solution</h3>
<p>[answer]</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>