<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sina Mokhtar">
<meta name="dcterms.date" content="2023-02-27">
<meta name="description" content="[Advanced Data Analysis 2](https://StatAcumen.com/teach/ada12, Stat 428/528, Spring 2023, Prof.&nbsp;Erik Erhardt, UNM">

<title>ADA2: Class 12, Ch 07a, Analysis of Covariance: Comparing Regression Lines</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/quarto-html/quarto.js"></script>
<script src="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/quarto-html/popper.min.js"></script>
<script src="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/quarto-html/anchor.min.js"></script>
<link href="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ADA2_CL_12_ANCOVA_FacultySalary_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ADA2: Class 12, Ch 07a, Analysis of Covariance: Comparing Regression Lines</h1>
</div>

<div>
  <div class="description">
    <p>[Advanced Data Analysis 2](https://StatAcumen.com/teach/ada12, Stat 428/528, Spring 2023, Prof.&nbsp;Erik Erhardt, UNM</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sina Mokhtar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 27, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>
<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#ancova-model-faculty-political-tolerances" id="toc-ancova-model-faculty-political-tolerances">ANCOVA model: Faculty political tolerances</a>
  <ul>
  <li><a href="#p-describe-the-plotted-fitted-regression-lines" id="toc-p-describe-the-plotted-fitted-regression-lines"><strong>(0 p)</strong> Describe the plotted fitted regression lines</a>
  <ul>
  <li><a href="#solution" id="toc-solution">Solution</a></li>
  </ul></li>
  <li><a href="#p-write-the-full-model-equation-with-indicator-variables." id="toc-p-write-the-full-model-equation-with-indicator-variables."><strong>(0 p)</strong> Write the full model equation with indicator variables.</a>
  <ul>
  <li><a href="#solution-1" id="toc-solution-1">Solution</a></li>
  </ul></li>
  <li><a href="#p-test-for-equal-slopes." id="toc-p-test-for-equal-slopes."><strong>(2 p)</strong> Test for equal slopes.</a>
  <ul>
  <li><a href="#solution-2" id="toc-solution-2">Solution</a></li>
  </ul></li>
  <li><a href="#p-reduce-the-model." id="toc-p-reduce-the-model."><strong>(1 p)</strong> Reduce the model.</a>
  <ul>
  <li><a href="#solution-3" id="toc-solution-3">Solution</a></li>
  </ul></li>
  <li><a href="#p-write-the-fitted-model-equation." id="toc-p-write-the-fitted-model-equation."><strong>(0 p)</strong> Write the fitted model equation.</a>
  <ul>
  <li><a href="#solution-4" id="toc-solution-4">Solution</a></li>
  </ul></li>
  <li><a href="#p-aside-regression-line-estimation-with-interaction" id="toc-p-aside-regression-line-estimation-with-interaction"><strong>(1 p)</strong> Aside: regression line estimation with interaction</a>
  <ul>
  <li><a href="#solution-5" id="toc-solution-5">Solution</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#additional-analyses-possible-directions" id="toc-additional-analyses-possible-directions">Additional analyses, possible directions</a>
  <ul>
  <li><a href="#p-direction-1-pairwise-comparison-of-regression-line-slope-between-ranks" id="toc-p-direction-1-pairwise-comparison-of-regression-line-slope-between-ranks"><strong>(0 p)</strong> Direction 1: pairwise comparison of regression line slope between ranks</a>
  <ul>
  <li><a href="#solution-6" id="toc-solution-6">Solution</a></li>
  </ul></li>
  <li><a href="#p-direction-2-pairwise-comparison-of-regression-lines-slope-and-intercept-between-ranks" id="toc-p-direction-2-pairwise-comparison-of-regression-lines-slope-and-intercept-between-ranks"><strong>(2 p)</strong> Direction 2: pairwise comparison of regression lines (slope and intercept) between ranks</a>
  <ul>
  <li><a href="#solution-7" id="toc-solution-7">Solution</a></li>
  </ul></li>
  <li><a href="#p-direction-3-exclude-ages-50-and-reanalyze" id="toc-p-direction-3-exclude-ages-50-and-reanalyze"><strong>(1 p)</strong> Direction 3: exclude ages <span class="math inline">\(&gt; 50\)</span> and reanalyze</a>
  <ul>
  <li><a href="#solution-8" id="toc-solution-8">Solution</a></li>
  </ul></li>
  <li><a href="#p-direction-4-combine-the-junior-faculty-asst-and-assoc" id="toc-p-direction-4-combine-the-junior-faculty-asst-and-assoc"><strong>(3 p)</strong> Direction 4: Combine the junior faculty (asst and assoc)</a>
  <ul>
  <li><a href="#solution-9" id="toc-solution-9">Solution</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
<section id="ancova-model-faculty-political-tolerances" class="level1">
<h1>ANCOVA model: Faculty political tolerances</h1>
<p>A political scientist developed a questionnaire to determine political tolerance scores for a random sample of faculty members at her university. She wanted to compare mean scores adjusted for the age for each of the three categories: full professors (coded 1), associate professors (coded 2), and assistant professors (coded 3). The data are given below. Note the higher the score, the more tolerant the individual.</p>
<p>Below we will fit and interpret a model to assess the dependence of tolerance score on age and rank.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(erikmisc)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── erikmisc 0.1.18 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ tibble 3.1.7      ✔ dplyr  1.0.10</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ─────────────────────────────────────────── erikmisc_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>erikmisc, solving common complex data analysis workflows
  by Dr. Erik Barry Erhardt &lt;erik@StatAcumen.com&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages
───────────────────────────────────────
tidyverse 1.3.2 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ ggplot2 3.4.0     ✔ purrr   1.0.1
✔ tidyr   1.2.1     ✔ stringr 1.5.0
✔ readr   2.1.2     ✔ forcats 0.5.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, download the data to your computer,</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   save in the same folder as this Rmd file.</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># read the data</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>dat_tolerate <span class="ot">&lt;-</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>(<span class="st">"ADA2_CL_12_tolerate.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># set 3="Asst" as baseline level</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">rank =</span> <span class="fu">factor</span>(rank) <span class="sc">%&gt;%</span> <span class="fu">relevel</span>(<span class="dv">3</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  , <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">n</span>()</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 30 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): score, age, rank

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dat_tolerate)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [30 × 4] (S3: tbl_df/tbl/data.frame)
 $ score: num [1:30] 3.03 4.31 5.09 3.71 5.29 2.7 2.7 4.02 5.52 4.62 ...
 $ age  : num [1:30] 65 47 49 41 40 61 52 45 41 39 ...
 $ rank : Factor w/ 3 levels "3","1","2": 2 2 2 2 2 2 2 2 2 2 ...
 $ id   : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...</code></pre>
</div>
</div>
<section id="p-describe-the-plotted-fitted-regression-lines" class="level2">
<h2 class="anchored" data-anchor-id="p-describe-the-plotted-fitted-regression-lines"><strong>(0 p)</strong> Describe the plotted fitted regression lines</h2>
<p>Below is a plot of tolerance against age, using rank as a plotting symbol. Describe how tolerance score depends on age within ranks.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<section id="solution" class="level3">
<h3 class="anchored" data-anchor-id="solution">Solution</h3>
<p>[answer]</p>
<p>The data plot suggests that tolerance decreases roughly linearly with age among the full professors (rank=1). The relationship between tolerance and age is much weaker (basically horizontal, no relationship) among the assistant professors (rank=3) and the associate professors (rank=2).</p>
</section>
</section>
<section id="p-write-the-full-model-equation-with-indicator-variables." class="level2">
<h2 class="anchored" data-anchor-id="p-write-the-full-model-equation-with-indicator-variables."><strong>(0 p)</strong> Write the full model equation with indicator variables.</h2>
<p>(You did this last class.)</p>
<p>Create indicators for full and associate professors, so that assistant professors serve as the reference group. Write the full model, then the separate model for each rank using general notation.</p>
<section id="solution-1" class="level3">
<h3 class="anchored" data-anchor-id="solution-1">Solution</h3>
<p>We are interested in creating a multiple regression model that allows each rank to have its own regression line. There are three ranks, so two indicator variables are needed to uniquely identify each faculty member by rank. To have assistant professors serve as the reference group, let <span class="math inline">\(I(\textrm{rank}=1)=1\)</span> for full professors (rank=1) and <span class="math inline">\(I(\textrm{rank}=1)=0\)</span> otherwise, and set <span class="math inline">\(I(\textrm{rank}=2)=1\)</span> for associate professors (rank=2) and <span class="math inline">\(I(\textrm{rank}=2)=0\)</span> otherwise. Also define the two interaction or product effects: <span class="math inline">\(I(\textrm{rank}=1)\textrm{ age}\)</span> and <span class="math inline">\(I(\textrm{rank}=2)\textrm{ age}\)</span>.</p>
<p>The model that allows separate slopes and intercepts for each rank is given by: <span class="math display">\[
  \textrm{score} = \beta_0 + \beta_1 I(\textrm{rank}=1) + \beta_2 I(\textrm{rank}=2) + \beta_3 \textrm{ age} + \beta_4 I(\textrm{rank}=1)\textrm{ age} +
                \beta_5 I(\textrm{rank}=2)\textrm{ age} + e.
\]</span> For later reference, the model will be expressed by considering the three faculty ranks separately. For assistant professors with rank = 3, we have <span class="math inline">\(I(\textrm{rank}=1)=I(\textrm{rank}=2)=0\)</span>, so <span class="math display">\[
  \textrm{score} \ = \ \beta_0 + \beta_3 \textrm{ age} + e.
\]</span> For associates with rank=2, we have <span class="math inline">\(I(\textrm{rank}=1)=0\)</span> and <span class="math inline">\(I(\textrm{rank}=2)=1\)</span>, which gives <span class="math display">\[
  \textrm{score} \ = \ \beta_0 + \beta_2(1) + \beta_3 \textrm{ age} + \beta_5 \textrm{ age} + e
      \ = \ (\beta_0 + \beta_2)  + (\beta_3 + \beta_5) \textrm{ age} + e.
\]</span> Lastly, for full professors with rank=1, we have <span class="math inline">\(I(\textrm{rank}=2)=0\)</span> and <span class="math inline">\(I(\textrm{rank}=1)=1\)</span>, so <span class="math display">\[
  \textrm{score} \ = \ \beta_0 + \beta_1(1) + \beta_3 \textrm{ age} + \beta_4 \textrm{ age} + e
      \ = \ (\beta_0 + \beta_1)  + (\beta_3 + \beta_4) \textrm{ age} + e.
\]</span></p>
<p>The regression coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_3\)</span> are the intercept and slope for the assistant professor population regression line. The other parameters measure differences in intercepts and slopes across the three groups, using assistant professors as a baseline or reference group. In particular:</p>
<p><span class="math inline">\(\beta_1 =\)</span> difference between the intercepts of the full and assistant professors population regression lines.</p>
<p><span class="math inline">\(\beta_2 =\)</span> difference between the intercepts of the associate and assistant professors population regression lines.</p>
<p><span class="math inline">\(\beta_4 =\)</span> difference between the slopes of the full and assistant professors population regression lines.</p>
<p><span class="math inline">\(\beta_5 =\)</span> difference between the slopes of the associate and assistant professors population regression lines.</p>
</section>
</section>
<section id="p-test-for-equal-slopes." class="level2">
<h2 class="anchored" data-anchor-id="p-test-for-equal-slopes."><strong>(2 p)</strong> Test for equal slopes.</h2>
<p>Starting with a model that allows each rank to have it’s own intercept and slope, test whether the slopes are equal. If the hypothesis of equal slopes is plausible, fit the model of equal slopes and test whether intercepts are equal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lm_s_a_r_ar <span class="ot">&lt;-</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    score <span class="sc">~</span> age <span class="sc">*</span> rank</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> dat_tolerate</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<p>In your answer, first assess model fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.05251352, Df = 1, p = 0.81875</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in e_plot_lm_diagostics(lm_s_a_r_ar): Note: Collinearity plot unreliable
for predictors that also have interactions in the model.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-4-5.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>Then, test the hypothesis of equal slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(<span class="fu">aov</span>(lm_s_a_r_ar), <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: score
             Sum Sq Df F value    Pr(&gt;F)    
(Intercept) 12.3528  1 30.3672 1.148e-05 ***
age          0.0817  1  0.2009   0.65802    
rank         2.6243  2  3.2257   0.05744 .  
age:rank     3.3610  2  4.1312   0.02872 *  
Residuals    9.7628 24                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="solution-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-2">Solution</h3>
<p>[answer] check assumptions:<br>
The residuals are roughly distributed normal based on QQplot. there are no significant outlier. the distribution of data in rank 1 and 3 group is wider in compare to rank 2 but the this difference is not big. There is not enough evidence that we can tell variance is not constant between all groups. based on box-cox plot we do not need transformation. In general all assumptions are met.</p>
<p>Since the interaction age:rank is significant (p-value = 0.02872 &lt; .05) so we can reject the null hypothesis (equal slopes) and as conclusion the slops are not equal.</p>
</section>
</section>
<section id="p-reduce-the-model." class="level2">
<h2 class="anchored" data-anchor-id="p-reduce-the-model."><strong>(1 p)</strong> Reduce the model.</h2>
<p>Given the tests in the previous part, reduce the model using backward selection.</p>
<ol type="1">
<li>Start with the full model, test for equal slopes.</li>
<li>If slopes are equal (not significantly for being different), then test for equal intercepts.</li>
<li>If intercepts are equal, test for any slope.</li>
<li>If slope is zero, then the grand mean intercept is the best model.</li>
</ol>
<section id="solution-3" class="level3">
<h3 class="anchored" data-anchor-id="solution-3">Solution</h3>
<p>[answer] The interaction is significant so Slops are not equals so the full model is acceptable and no need to reduction.</p>
</section>
</section>
<section id="p-write-the-fitted-model-equation." class="level2">
<h2 class="anchored" data-anchor-id="p-write-the-fitted-model-equation."><strong>(0 p)</strong> Write the fitted model equation.</h2>
<p>Last class you wrote these model equations. Modify to your reduced model if necessary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ age * rank, data = dat_tolerate)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.34746 -0.28793  0.01405  0.36653  1.07669 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.42706    0.98483   5.511 1.15e-05 ***
age         -0.01321    0.02948  -0.448   0.6580    
rank1        2.78490    1.51591   1.837   0.0786 .  
rank2       -1.22343    1.50993  -0.810   0.4258    
age:rank1   -0.07247    0.03779  -1.918   0.0671 .  
age:rank2    0.03022    0.04165   0.726   0.4751    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6378 on 24 degrees of freedom
Multiple R-squared:  0.5112,    Adjusted R-squared:  0.4093 
F-statistic:  5.02 on 5 and 24 DF,  p-value: 0.002748</code></pre>
</div>
</div>
<section id="solution-4" class="level3">
<h3 class="anchored" data-anchor-id="solution-4">Solution</h3>
<p>Modify if your reduced model is different.</p>
<p>1: full professors <span class="math display">\[\widehat{\textrm{score}} = 5.427 + 2.785 + (-0.013 -0.072) \textrm{ age} = 8.212 - 0.085 \textrm{ age}\]</span></p>
<p>2: associate professors <span class="math display">\[\widehat{\textrm{score}} = 5.427 - 1.223 + (-0.013 +0.030) \textrm{ age} = 4.204 + 0.017 \textrm{ age}\]</span></p>
<p>3: assistant professors <span class="math display">\[\widehat{\textrm{score}} = 5.427 - 0.013 \textrm{ age}\]</span></p>
</section>
</section>
<section id="p-aside-regression-line-estimation-with-interaction" class="level2">
<h2 class="anchored" data-anchor-id="p-aside-regression-line-estimation-with-interaction"><strong>(1 p)</strong> Aside: regression line estimation with interaction</h2>
<p>(The question is at the bottom of this exposition.)</p>
<p>One feature to notice is that the observation 7 in the group of full professors appears to have an unusually low tolerance for his age (2.70 52 1). If you temporarily hold this observation out of the analysis, you still conclude that the population regression lines have different slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exclude observation 7 from tolerate7 dataset</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>dat_tolerate7 <span class="ot">&lt;-</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  dat_tolerate <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="sc">-</span><span class="dv">7</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>lm7_s_a_r_ar <span class="ot">&lt;-</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    score <span class="sc">~</span> age <span class="sc">*</span> rank</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> dat_tolerate7</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(<span class="fu">aov</span>(lm7_s_a_r_ar), <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: score
             Sum Sq Df F value    Pr(&gt;F)    
(Intercept) 12.3528  1 33.4564 6.821e-06 ***
age          0.0817  1  0.2213   0.64245    
rank         2.3381  2  3.1662   0.06100 .  
age:rank     2.8667  2  3.8821   0.03526 *  
Residuals    8.4921 23                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm7_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ age * rank, data = dat_tolerate7)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.34746 -0.31099  0.01162  0.30310  0.94978 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.42706    0.93827   5.784 6.82e-06 ***
age         -0.01321    0.02808  -0.470   0.6425    
rank1        2.58793    1.44812   1.787   0.0871 .  
rank2       -1.22343    1.43853  -0.850   0.4038    
age:rank1   -0.06586    0.03618  -1.821   0.0817 .  
age:rank2    0.03022    0.03968   0.762   0.4540    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6076 on 23 degrees of freedom
Multiple R-squared:  0.4706,    Adjusted R-squared:  0.3555 
F-statistic: 4.088 on 5 and 23 DF,  p-value: 0.0084</code></pre>
</div>
</div>
<p>This observation has a fairly large impact on the estimated intercept and slope for the full professor regression line, <strong>but has no effect whatsoever on the estimated intercepts or slopes for the two other ranks. Why?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># full data set</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_s_a_r_ar)  <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">4</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age       rank1       rank2   age:rank1   age:rank2 
     5.4271     -0.0132      2.7849     -1.2234     -0.0725      0.0302 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># without obs 7</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm7_s_a_r_ar) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">4</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age       rank1       rank2   age:rank1   age:rank2 
     5.4271     -0.0132      2.5879     -1.2234     -0.0659      0.0302 </code></pre>
</div>
</div>
<section id="solution-5" class="level3">
<h3 class="anchored" data-anchor-id="solution-5">Solution</h3>
<p>[answer] when we include interaction we determined a regression line separately for each group, so the slope and intercept of the regression for each group is the one that minimize the least squares for that group only based on the data for that specific group. so when we remove a point from prof group it only effect the slope and intercept of prof group. However it would effect the residual standard error which uses to calculating the p-values (it would effect the hypothesis test).</p>
</section>
</section>
</section>
<section id="additional-analyses-possible-directions" class="level1">
<h1>Additional analyses, possible directions</h1>
<p>We’ll explore four possible sets of additional analyses that help us understand the relationships we found.</p>
<p>There are a number of possible directions here. We found earlier that there was an interaction, so there’s evidence for different slopes.</p>
<ol type="1">
<li><p>Use the Wald test to perform pairwise comparisons for the <strong>regression line slope</strong> between ranks.</p></li>
<li><p>Use the Wald test to perform pairwise comparisons for the <strong>regression line slope and intercept</strong> between ranks.</p></li>
<li><p>Observe that Full professors (rank = 1) are the only ones that have ages greater than 50, and those three observations are systematically different from scores for faculty not older than 50 – thus <strong>these three observations could be removed</strong> and inference could be limited to faculty from 25–50 years old.</p></li>
<li><p>Combine the junior faculty (<strong>assistant and associate: AA</strong>).</p></li>
</ol>
<p>Other ideas are possible, but these are enough.</p>
<section id="p-direction-1-pairwise-comparison-of-regression-line-slope-between-ranks" class="level2">
<h2 class="anchored" data-anchor-id="p-direction-1-pairwise-comparison-of-regression-line-slope-between-ranks"><strong>(0 p)</strong> Direction 1: pairwise comparison of regression line slope between ranks</h2>
<p>I’ll get you started using the Wald test to set up 1+ degree-of-freedom hypothesis tests.</p>
<p>Earlier we found that slopes are different. We will use the Wald test to perform comparisons of slopes between pairs of ranks.</p>
<p>We’ll discuss the linear algebra specification of these hypothesis test in class.</p>
<section id="solution-6" class="level3">
<h3 class="anchored" data-anchor-id="solution-6">Solution</h3>
<p>The tests below indicate that there’s an interaction because the slopes for Ranks 1 and 2 differ. Because we’re performing three tests, it is appropriate to compare these p-values to a significance level controlling the familywise Type-I error rate; the Bonferroni threshold is 0.05/3=0.01667.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first, find the order of the coefficients</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age       rank1       rank2   age:rank1   age:rank2 
 5.42706473 -0.01321299  2.78490230 -1.22343359 -0.07247382  0.03022001 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aod) <span class="co"># for wald.test()</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="do">## H0: Slope of Rank 1 = Rank 3 (similar to summary table above)</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>mR <span class="ot">&lt;-</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>()</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>vR <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>test_wald <span class="ot">&lt;-</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wald.test</span>(</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">b     =</span> <span class="fu">coef</span>(lm_s_a_r_ar)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  , <span class="at">Sigma =</span> <span class="fu">vcov</span>(lm_s_a_r_ar)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  , <span class="at">L     =</span> mR</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  , <span class="at">H0    =</span> vR</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>test_wald</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 3.7, df = 1, P(&gt; X2) = 0.055</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="do">## H0: Slope of Rank 2 = Rank 3 (similar to summary table above)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>mR <span class="ot">&lt;-</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>()</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>vR <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>test_wald <span class="ot">&lt;-</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wald.test</span>(</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">b     =</span> <span class="fu">coef</span>(lm_s_a_r_ar)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  , <span class="at">Sigma =</span> <span class="fu">vcov</span>(lm_s_a_r_ar)</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  , <span class="at">L     =</span> mR</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>  , <span class="at">H0    =</span> vR</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>test_wald</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 0.53, df = 1, P(&gt; X2) = 0.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="do">## H0: Slope of Rank 1 = Rank 2 (not in summary table above)</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>mR <span class="ot">&lt;-</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>()</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>vR <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>test_wald <span class="ot">&lt;-</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wald.test</span>(</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">b     =</span> <span class="fu">coef</span>(lm_s_a_r_ar)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  , <span class="at">Sigma =</span> <span class="fu">vcov</span>(lm_s_a_r_ar)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>  , <span class="at">L     =</span> mR</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  , <span class="at">H0    =</span> vR</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>test_wald</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 7.4, df = 1, P(&gt; X2) = 0.0065</code></pre>
</div>
</div>
</section>
</section>
<section id="p-direction-2-pairwise-comparison-of-regression-lines-slope-and-intercept-between-ranks" class="level2">
<h2 class="anchored" data-anchor-id="p-direction-2-pairwise-comparison-of-regression-lines-slope-and-intercept-between-ranks"><strong>(2 p)</strong> Direction 2: pairwise comparison of regression lines (slope and intercept) between ranks</h2>
<p>To test whether the regression line is different between ranks, in the null hypothesis <span class="math inline">\(H_0\)</span> we need to set both the slope and the intercept equal between a selected pair of ranks.</p>
<p>Here’s the first example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first, find the order of the coefficients</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age       rank1       rank2   age:rank1   age:rank2 
 5.42706473 -0.01321299  2.78490230 -1.22343359 -0.07247382  0.03022001 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aod) <span class="co"># for wald.test()</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="do">## H0: Line of Rank 1 = Rank 3</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>mR <span class="ot">&lt;-</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  , <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>()</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>vR <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>test_wald <span class="ot">&lt;-</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wald.test</span>(</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">b     =</span> <span class="fu">coef</span>(lm_s_a_r_ar)</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>  , <span class="at">Sigma =</span> <span class="fu">vcov</span>(lm_s_a_r_ar)</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>  , <span class="at">L     =</span> mR</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>  , <span class="at">H0    =</span> vR</span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>test_wald</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 3.7, df = 2, P(&gt; X2) = 0.16</code></pre>
</div>
</div>
<section id="solution-7" class="level3">
<h3 class="anchored" data-anchor-id="solution-7">Solution</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="do">## H0: Line of Rank 2 = Rank 3</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>mR <span class="ot">&lt;-</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  , <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>()</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>vR <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>test_wald <span class="ot">&lt;-</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wald.test</span>(</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">b     =</span> <span class="fu">coef</span>(lm_s_a_r_ar)</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>  , <span class="at">Sigma =</span> <span class="fu">vcov</span>(lm_s_a_r_ar)</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  , <span class="at">L     =</span> mR</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  , <span class="at">H0    =</span> vR</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>test_wald</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 0.77, df = 2, P(&gt; X2) = 0.68</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="do">## H0: Line of Rank 1 = Rank 2</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>mR <span class="ot">&lt;-</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  , <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>()</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>vR <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>test_wald <span class="ot">&lt;-</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wald.test</span>(</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">b     =</span> <span class="fu">coef</span>(lm_s_a_r_ar)</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  , <span class="at">Sigma =</span> <span class="fu">vcov</span>(lm_s_a_r_ar)</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>  , <span class="at">L     =</span> mR</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>  , <span class="at">H0    =</span> vR</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>test_wald</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 8.3, df = 2, P(&gt; X2) = 0.016</code></pre>
</div>
</div>
<p>[answer] Test01: we do not have evidence that full prof and assistant have the same regression line. Test02: we do not have evidence that associate and assistant have the same regression line. Test03: since the p-value is less than .05 we reject the null hypothesis(same regression line) and as conclusion the associate and full prof do not have the same regression line.</p>
</section>
</section>
<section id="p-direction-3-exclude-ages-50-and-reanalyze" class="level2">
<h2 class="anchored" data-anchor-id="p-direction-3-exclude-ages-50-and-reanalyze"><strong>(1 p)</strong> Direction 3: exclude ages <span class="math inline">\(&gt; 50\)</span> and reanalyze</h2>
<p>Drop observations with <code>age &gt; 50</code> and refit the model. Remember to check model assumptions, then do backward selection (manually), then check the final model assumptions.</p>
<section id="solution-8" class="level3">
<h3 class="anchored" data-anchor-id="solution-8">Solution</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>newdat <span class="ot">=</span> dat_tolerate <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    age<span class="sc">&lt;</span><span class="dv">50</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>lm_s_a_r_ar <span class="ot">&lt;-</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>    score <span class="sc">~</span> age <span class="sc">*</span> rank</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> newdat</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>In your answer, first assess model fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.2436666, Df = 1, p = 0.62157</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in e_plot_lm_diagostics(lm_s_a_r_ar): Note: Collinearity plot unreliable
for predictors that also have interactions in the model.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-15-5.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>Then, test the hypothesis of equal slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(<span class="fu">aov</span>(lm_s_a_r_ar), <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: score
             Sum Sq Df F value    Pr(&gt;F)    
(Intercept) 12.3528  1 32.9025 1.079e-05 ***
age          0.0817  1  0.2177    0.6456    
rank         0.2801  2  0.3731    0.6931    
age:rank     0.2480  2  0.3303    0.7224    
Residuals    7.8842 21                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>check assumptions:<br>
The residuals are roughly distributed normal based on QQplot. the observation 2 is influential but there are no significant outlier. the distribution of data in rank 1 and 3 group is wider in compare to rank 2 but the this difference is not big. There is not enough evidence that we can tell variance is not constant between all groups. based on box-cox plot we do not need transformation. In general all assumptions are met.</p>
<p>Since the interaction age:rank is not significant (p-value = .72 &gt; .05) so we can not reject the null hypothesis so there is no interaction between age and rank.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>lm_s_a_r_ar <span class="ot">&lt;-</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>    score <span class="sc">~</span> age <span class="sc">+</span> rank</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> newdat</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.06355161, Df = 1, p = 0.80097</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-18-3.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in e_plot_lm_diagostics(lm_s_a_r_ar): Note: Collinearity plot unreliable
for predictors that also have interactions in the model.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-18-4.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-18-5.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>Then, test the hypothesis of equal slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(<span class="fu">aov</span>(lm_s_a_r_ar), <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: score
             Sum Sq Df F value    Pr(&gt;F)    
(Intercept) 21.8175  1 61.7061 5.858e-08 ***
age          0.0000  1  0.0001    0.9930    
rank         0.3429  2  0.4848    0.6219    
Residuals    8.1322 23                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ age + rank, data = newdat)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.32472 -0.36970 -0.00364  0.35972  0.86892 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.9896329  0.6351915   7.855 5.86e-08 ***
age          0.0001641  0.0185542   0.009    0.993    
rank1       -0.3452854  0.3512975  -0.983    0.336    
rank2       -0.1409191  0.2855001  -0.494    0.626    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5946 on 23 degrees of freedom
Multiple R-squared:  0.0564,    Adjusted R-squared:  -0.06668 
F-statistic: 0.4583 on 3 and 23 DF,  p-value: 0.7141</code></pre>
</div>
</div>
<p>check assumptions:<br>
The residuals are roughly distributed normal based on QQplot. the observation 22 is influential but there are no significant outlier. the distribution of data in rank 1 and 3 group is wider in compare to rank 2 but the this difference is not big. There is not enough evidence that we can tell variance is not constant between all groups. based on box-cox plot we do not need transformation. In general all assumptions are met.</p>
<p>Since the p-value is not significant so there is not enough evidence for different intercept so we can remove the rank from the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>lm_s_a_r_ar <span class="ot">&lt;-</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>    score <span class="sc">~</span> age</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> newdat</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.4899539, Df = 1, p = 0.48395</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in e_plot_lm_diagostics(lm_s_a_r_ar): Collinearity plot only available
with at least two predictor (x) variables.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-21-3.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>Then, test the hypothesis of equal slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(<span class="fu">aov</span>(lm_s_a_r_ar), <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: score
             Sum Sq Df F value    Pr(&gt;F)    
(Intercept) 27.7698  1 81.9167 2.306e-09 ***
age          0.1432  1  0.4225    0.5216    
Residuals    8.4750 25                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ age, data = newdat)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.24769 -0.36315 -0.03972  0.36398  0.96194 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.221970   0.576963   9.051 2.31e-09 ***
age         -0.009815   0.015100  -0.650    0.522    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5822 on 25 degrees of freedom
Multiple R-squared:  0.01662,   Adjusted R-squared:  -0.02272 
F-statistic: 0.4225 on 1 and 25 DF,  p-value: 0.5216</code></pre>
</div>
</div>
<p>check assumptions:<br>
The residuals are roughly distributed normal based on QQplot. the observation 22 is influential but there are no significant outlier. the distribution of data in rank 1 and 3 group is wider in compare to rank 2 but the this difference is not big. There is not enough evidence that we can tell variance is not constant between all groups. based on box-cox plot we do not need transformation. In general all assumptions are met.</p>
<p>Since the p-value is not significant so there is not enough evidence for a slope for age different from one. so we replace age with one and fitt the model again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>lm_s_a_r_ar <span class="ot">&lt;-</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>    score <span class="sc">~</span> <span class="dv">1</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> newdat</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>Then, test the hypothesis of equal slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(<span class="fu">aov</span>(lm_s_a_r_ar), <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: score
            Sum Sq Df F value    Pr(&gt;F)    
(Intercept) 636.17  1  1919.2 &lt; 2.2e-16 ***
Residuals     8.62 26                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ 1, data = newdat)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.18407 -0.34907 -0.00407  0.36093  1.00593 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   4.8541     0.1108   43.81   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5757 on 26 degrees of freedom</code></pre>
</div>
</div>
<p>so 4.85 is the grand mean and is the simplest and final model.</p>
</section>
</section>
<section id="p-direction-4-combine-the-junior-faculty-asst-and-assoc" class="level2">
<h2 class="anchored" data-anchor-id="p-direction-4-combine-the-junior-faculty-asst-and-assoc"><strong>(3 p)</strong> Direction 4: Combine the junior faculty (asst and assoc)</h2>
<p>Create a new factor variable <code>rankaa</code> that combines ranks 2 and 3 as value <code>0</code>, but has rank 1 still value <code>1</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>dat_tolerate <span class="ot">&lt;-</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  dat_tolerate <span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># indicator for Full vs (Assist &amp; Assoc)</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">rankaa =</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">case_when</span>(</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>        rank <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>) <span class="sc">~</span> <span class="dv">0</span>     <span class="co"># Assist &amp; Assoc</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>      , rank <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>   ) <span class="sc">~</span> <span class="dv">1</span>     <span class="co"># Full</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>  , <span class="at">rankaa =</span> <span class="fu">factor</span>(rankaa)</span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a>  , <span class="at">rankaa =</span> <span class="fu">relevel</span>(rankaa, <span class="st">"0"</span>)</span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<p>Note that in Direction 2 above we tested whether the assistants and the associates have the same population regression line and found they were not statistically different. We had performed a simultaneous hypothesis test, same as below. (Note that this is an alternate way to do the simultaneous test when we are testing that the coefficients are equal to zero (using <code>Terms = c(4, 6)</code>); we did this differently above because I wanted to show the more general way of comparing whether coefficients were also equal to each other or possibly equal to a value different from zero).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>lm_s_a_r_ar <span class="ot">&lt;-</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>    score <span class="sc">~</span> age <span class="sc">*</span> rank</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> dat_tolerate</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age       rank1       rank2   age:rank1   age:rank2 
 5.42706473 -0.01321299  2.78490230 -1.22343359 -0.07247382  0.03022001 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aod) <span class="co"># for wald.test()</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Typically, we are interested in testing whether individual parameters or</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   set of parameters are all simultaneously equal to 0s</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a><span class="co"># However, any null hypothesis values can be included in the vector coef.test.values.</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>coef_test_values <span class="ot">&lt;-</span></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(<span class="fu">coef</span>(lm_s_a_r_ar)))</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aod) <span class="co"># for wald.test()</span></span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>test_wald <span class="ot">&lt;-</span></span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wald.test</span>(</span>
<span id="cb85-12"><a href="#cb85-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">b     =</span> <span class="fu">coef</span>(lm_s_a_r_ar) <span class="sc">-</span> coef_test_values</span>
<span id="cb85-13"><a href="#cb85-13" aria-hidden="true" tabindex="-1"></a>  , <span class="at">Sigma =</span> <span class="fu">vcov</span>(lm_s_a_r_ar)</span>
<span id="cb85-14"><a href="#cb85-14" aria-hidden="true" tabindex="-1"></a>  , <span class="at">Terms =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">6</span>)</span>
<span id="cb85-15"><a href="#cb85-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb85-16"><a href="#cb85-16" aria-hidden="true" tabindex="-1"></a>test_wald</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 0.77, df = 2, P(&gt; X2) = 0.68</code></pre>
</div>
</div>
<p>The p-value for this test is approximately 0.7, which suggests that the population regression lines for these two groups are not significantly different.</p>
<p>At this point I would refit the model, omitting the <span class="math inline">\(I(\textrm{rank}=2)\)</span> and <span class="math inline">\(I(\textrm{rank}=2)\textrm{ age}\)</span> effects. <span class="math display">\[
  \textrm{score} = \beta_0 + \beta_1 I(\textrm{rank}=1) + \beta_3 \textrm{ age} + \beta_4 I(\textrm{rank}=1)\textrm{ age} + e.
\]</span> This model produces two distinct regression lines, one for the full professors and one for the combined assistants and associates.</p>
<p><strong>Do this.</strong></p>
<p>Using the combined AA rank data, do the following and interpret each result:</p>
<ol type="1">
<li>plot the data</li>
<li>fit the full interaction model, reduce if possible</li>
<li>write out the separate model equations for the Full and AA ranks</li>
<li>check model assumptions</li>
<li>reduce the model (if appropriate) and recheck assumptions</li>
</ol>
<section id="solution-9" class="level3">
<h3 class="anchored" data-anchor-id="solution-9">Solution</h3>
<p>[answer]</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>lm_s_a_r_ar <span class="ot">&lt;-</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>    score <span class="sc">~</span> age <span class="sc">*</span> rankaa</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> dat_tolerate</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age      rankaa1  age:rankaa1 
 4.993406393 -0.001926941  3.218560640 -0.083759873 </code></pre>
</div>
</div>
<p>In your answer, first assess model fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-30-2.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.1326644, Df = 1, p = 0.71569</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-30-3.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in e_plot_lm_diagostics(lm_s_a_r_ar): Note: Collinearity plot unreliable
for predictors that also have interactions in the model.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-30-4.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_12_ANCOVA_FacultySalary_files/figure-html/unnamed-chunk-30-5.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>check assumptions:<br>
The residuals are roughly distributed normal based on QQplot. there are no significant outlier. There is not enough evidence that we can tell variance is not constant between two groups. based on box-cox plot we do not need transformation. In general all assumptions are met.</p>
<p>Then, test the hypothesis of equal slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(<span class="fu">aov</span>(lm_s_a_r_ar), <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: score
             Sum Sq Df F value    Pr(&gt;F)    
(Intercept) 20.7626  1 53.5843 8.971e-08 ***
age          0.0041  1  0.0105  0.919197    
rankaa       2.3197  1  5.9867  0.021486 *  
age:rankaa   3.0678  1  7.9175  0.009203 ** 
Residuals   10.0744 26                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_s_a_r_ar)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ age * rankaa, data = dat_tolerate)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.26367 -0.37032 -0.05807  0.33922  1.07669 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.993406   0.682148   7.320 8.97e-08 ***
age         -0.001927   0.018811  -0.102   0.9192    
rankaa1      3.218561   1.315436   2.447   0.0215 *  
age:rankaa1 -0.083760   0.029768  -2.814   0.0092 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6225 on 26 degrees of freedom
Multiple R-squared:  0.4956,    Adjusted R-squared:  0.4374 
F-statistic: 8.515 on 3 and 26 DF,  p-value: 0.0004174</code></pre>
</div>
</div>
<p>Since the interaction is significant so this is the final model <span class="math display">\[
  \textrm{score} = \beta_0 + \beta_1 I(\textrm{rankaa}=1) + \beta_3 \textrm{ age} + \beta_4 I(\textrm{rankaa}=1)\textrm{ age}.
\]</span></p>
<p><span class="math display">\[
  \widehat{\textrm{score}} = 4.993406 + 3.218561 * I(\textrm{rankaa}=1) + -0.001927 * \textrm{ age} + -0.083760 * I(\textrm{rankaa}=1)\textrm{ age}.
\]</span></p>
<p>1: full professors <span class="math display">\[\widehat{\textrm{score}} = 4.993406 + 3.218561 + (-0.001927 -0.083760) \textrm{ age} = 8.212 - 0.085 \textrm{ age}\]</span></p>
<p>2: associate and assistant professors <span class="math display">\[\widehat{\textrm{score}} = 4.993406  -0.001927 * \textrm{ age}\]</span></p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>