<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sina Mokhtar">
<meta name="dcterms.date" content="2023-02-20">
<meta name="description" content="[Advanced Data Analysis 2](https://StatAcumen.com/teach/ada12, Stat 428/528, Spring 2023, Prof.&nbsp;Erik Erhardt, UNM">

<title>ADA2: Class 10, Ch 05b Paired Experiments and Randomized Block Experiments: Two-way Factor design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="ADA2_CL_10_Exp_TwoWay-kang_files/libs/quarto-html/quarto.js"></script>
<script src="ADA2_CL_10_Exp_TwoWay-kang_files/libs/quarto-html/popper.min.js"></script>
<script src="ADA2_CL_10_Exp_TwoWay-kang_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ADA2_CL_10_Exp_TwoWay-kang_files/libs/quarto-html/anchor.min.js"></script>
<link href="ADA2_CL_10_Exp_TwoWay-kang_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ADA2_CL_10_Exp_TwoWay-kang_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ADA2_CL_10_Exp_TwoWay-kang_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ADA2_CL_10_Exp_TwoWay-kang_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ADA2_CL_10_Exp_TwoWay-kang_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ADA2: Class 10, Ch 05b Paired Experiments and Randomized Block Experiments: Two-way Factor design</h1>
</div>

<div>
  <div class="description">
    <p>[Advanced Data Analysis 2](https://StatAcumen.com/teach/ada12, Stat 428/528, Spring 2023, Prof.&nbsp;Erik Erhardt, UNM</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sina Mokhtar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>
<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#kangaroos-skull-measurements-mandible-length" id="toc-kangaroos-skull-measurements-mandible-length">Kangaroos skull measurements: mandible length</a>
  <ul>
  <li><a href="#p-interpret-plots-of-the-data-distributional-centers-and-shapes" id="toc-p-interpret-plots-of-the-data-distributional-centers-and-shapes"><strong>(1 p)</strong> Interpret plots of the data, distributional centers and shapes</a>
  <ul>
  <li><a href="#solution" id="toc-solution">Solution</a></li>
  </ul></li>
  <li><a href="#p-do-the-plots-above-suggest-there-is-an-interaction" id="toc-p-do-the-plots-above-suggest-there-is-an-interaction"><strong>(1 p)</strong> Do the plots above suggest there is an interaction?</a>
  <ul>
  <li><a href="#solution-1" id="toc-solution-1">Solution</a></li>
  </ul></li>
  <li><a href="#fit-the-two-way-interaction-model" id="toc-fit-the-two-way-interaction-model">Fit the two-way interaction model</a>
  <ul>
  <li><a href="#solution-2" id="toc-solution-2">Solution</a></li>
  </ul></li>
  <li><a href="#p-check-model-assumptions-for-full-model" id="toc-p-check-model-assumptions-for-full-model"><strong>(1 p)</strong> Check model assumptions for full model</a>
  <ul>
  <li><a href="#solution-3" id="toc-solution-3">Solution</a></li>
  </ul></li>
  <li><a href="#p-anova-table-test-for-interaction-and-main-effects" id="toc-p-anova-table-test-for-interaction-and-main-effects"><strong>(3 p)</strong> ANOVA table, test for interaction and main effects</a>
  <ul>
  <li><a href="#solution-4" id="toc-solution-4">Solution</a></li>
  </ul></li>
  <li><a href="#p-reduce-to-final-model-test-assumptions" id="toc-p-reduce-to-final-model-test-assumptions"><strong>(1 p)</strong> Reduce to final model, test assumptions</a>
  <ul>
  <li><a href="#solution-5" id="toc-solution-5">Solution</a></li>
  </ul></li>
  <li><a href="#p-summarize-the-differences" id="toc-p-summarize-the-differences"><strong>(2 p)</strong> Summarize the differences</a>
  <ul>
  <li><a href="#solution-6" id="toc-solution-6">Solution</a></li>
  <li><a href="#solution-7" id="toc-solution-7">Solution</a></li>
  </ul></li>
  <li><a href="#p-summarize-the-results-in-a-few-sentences" id="toc-p-summarize-the-results-in-a-few-sentences"><strong>(1 p)</strong> Summarize the results in a few sentences</a>
  <ul>
  <li><a href="#solution-8" id="toc-solution-8">Solution</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
<section id="kangaroos-skull-measurements-mandible-length" class="level1">
<h1>Kangaroos skull measurements: mandible length</h1>
<p><em>What effect does sex and species have on the mandible length of a kangaroo skull?</em></p>
<p>The data to be analyzed here are selected skull measurements on 148 kangaroos of known sex and species. There are 11 columns of data, corresponding to the following features. The measurements are in meters/10000 (mm/10).</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>column</th>
<th>Variable name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 *</td>
<td>sex</td>
<td>sex (1=M, 2=F)</td>
</tr>
<tr class="even">
<td>2 *</td>
<td>species</td>
<td>species (0=M. giganteus, 1=M.f. melanops, 2=M.f. fuliginosus)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>pow</td>
<td>post orbit width</td>
</tr>
<tr class="even">
<td>4</td>
<td>rw</td>
<td>rostal width</td>
</tr>
<tr class="odd">
<td>5</td>
<td>sopd</td>
<td>supra-occipital - paroccipital depth</td>
</tr>
<tr class="even">
<td>6</td>
<td>cw</td>
<td>crest width</td>
</tr>
<tr class="odd">
<td>7</td>
<td>ifl</td>
<td>incisive foramina length</td>
</tr>
<tr class="even">
<td>8 *</td>
<td>ml</td>
<td>mandible length</td>
</tr>
<tr class="odd">
<td>9</td>
<td>mw</td>
<td>mandible width</td>
</tr>
<tr class="even">
<td>10</td>
<td>md</td>
<td>mandible depth</td>
</tr>
<tr class="odd">
<td>11</td>
<td>arh</td>
<td>ascending ramus height</td>
</tr>
</tbody>
</table>
<p>Some of the observations in the data set are missing (not available). These are represented by a period <code>.</code>, which in the <code>read_csv()</code> function is specified by the <code>na = "."</code> option.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(erikmisc)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── erikmisc 0.1.18 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ tibble 3.1.7      ✔ dplyr  1.0.10</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ─────────────────────────────────────────── erikmisc_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>erikmisc, solving common complex data analysis workflows
  by Dr. Erik Barry Erhardt &lt;erik@StatAcumen.com&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages
───────────────────────────────────────
tidyverse 1.3.2 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ ggplot2 3.4.0     ✔ purrr   1.0.1
✔ tidyr   1.2.1     ✔ stringr 1.5.0
✔ readr   2.1.2     ✔ forcats 0.5.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, download the data to your computer,</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   save in the same folder as this Rmd file.</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>dat_kang <span class="ot">&lt;-</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ADA2_CL_09_kang.csv"</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  , <span class="at">na =</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">"."</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># subset only our columns of interest</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    sex, species, ml</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make dose a factor variable and label the levels</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex     =</span> <span class="fu">factor</span>(sex    , <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"M"</span>,<span class="st">"F"</span>))</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  , <span class="at">species =</span> <span class="fu">factor</span>(species, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Mg"</span>, <span class="st">"Mfm"</span>, <span class="st">"Mff"</span>))</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 148 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (11): sex, species, pow, rw, sopd, cw, ifl, ml, mw, md, arh

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove observations with missing values</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n_start  <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat_kang)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>dat_kang <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(dat_kang)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>n_keep   <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat_kang)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>n_drop   <span class="ot">&lt;-</span> n_start <span class="sc">-</span> n_keep</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Removed"</span>, n_start, <span class="st">"-"</span>, n_keep, <span class="st">"="</span>, n_drop, <span class="st">"observations with missing values."</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Removed 148 - 136 = 12 observations with missing values.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The first few observations</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat_kang)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  sex   species    ml
  &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;
1 M     Mg       1086
2 M     Mg       1158
3 M     Mg       1131
4 M     Mg       1090
5 M     Mg       1175
6 M     Mg        901</code></pre>
</div>
</div>
<section id="p-interpret-plots-of-the-data-distributional-centers-and-shapes" class="level2">
<h2 class="anchored" data-anchor-id="p-interpret-plots-of-the-data-distributional-centers-and-shapes"><strong>(1 p)</strong> Interpret plots of the data, distributional centers and shapes</h2>
<p>The side-by-side boxplots of the data compare the mandible lengths across the 6 combinations of sex and species. Comment on the distributional shapes and compare the typical mandible lengths across groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the cell means for each (sex, species) combination</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Group means</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>kang_mean     <span class="ot">&lt;-</span> dat_kang <span class="sc">%&gt;%</span>                            dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">m =</span> <span class="fu">mean</span>(ml))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>kang_mean_x   <span class="ot">&lt;-</span> dat_kang <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex)          <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">m =</span> <span class="fu">mean</span>(ml)) <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>kang_mean_s   <span class="ot">&lt;-</span> dat_kang <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(species)      <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">m =</span> <span class="fu">mean</span>(ml)) <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>()</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>kang_mean_xs  <span class="ot">&lt;-</span> dat_kang <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex, species) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">m =</span> <span class="fu">mean</span>(ml)) <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>()</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>kang_mean</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      m
  &lt;dbl&gt;
1 1247.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>kang_mean_x</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex       m
  &lt;fct&gt; &lt;dbl&gt;
1 M     1290.
2 F     1211.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>kang_mean_s</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  species     m
  &lt;fct&gt;   &lt;dbl&gt;
1 Mg      1257.
2 Mfm     1228.
3 Mff     1257.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>kang_mean_xs</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  sex   species     m
  &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;
1 M     Mg      1266.
2 M     Mfm     1254.
3 M     Mff     1362.
4 F     Mg      1249.
5 F     Mfm     1205.
6 F     Mff     1178.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interaction plots, ggplot</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat_kang, <span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> ml, <span class="at">colour =</span> species))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">#p1 &lt;- p1 + geom_hline(aes(yintercept = 0), colour = "black"</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co">#                  , linetype = "solid", size = 0.2, alpha = 0.3)</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> p1 <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">outlier.size=</span><span class="fl">0.1</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> p1 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> kang_mean_xs, <span class="fu">aes</span>(<span class="at">y =</span> m), <span class="at">size =</span> <span class="dv">4</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> p1 <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">data =</span> kang_mean_xs, <span class="fu">aes</span>(<span class="at">y =</span> m, <span class="at">group =</span> species), <span class="at">size =</span> <span class="fl">1.5</span>)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> p1 <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Kangaroo interaction plot, species by sex"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#print(p1)</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat_kang, <span class="fu">aes</span>(<span class="at">x =</span> species, <span class="at">y =</span> ml, <span class="at">colour =</span> sex))</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">#p2 &lt;- p2 + geom_hline(aes(yintercept = 0), colour = "black"</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co">#                  , linetype = "solid", size = 0.2, alpha = 0.3)</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> p2 <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">outlier.size=</span><span class="fl">0.1</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> p2 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> kang_mean_xs, <span class="fu">aes</span>(<span class="at">y =</span> m), <span class="at">size =</span> <span class="dv">4</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> p2 <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">data =</span> kang_mean_xs, <span class="fu">aes</span>(<span class="at">y =</span> m, <span class="at">group =</span> sex), <span class="at">size =</span> <span class="fl">1.5</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> p2 <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Kangaroo interaction plot, sex by species"</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co">#print(p2)</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'

The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> <span class="fu">list</span>(p1, p2), <span class="at">nrow=</span><span class="dv">1</span>, <span class="at">top=</span><span class="st">"Kangaroo crestwidth plots"</span>)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_10_Exp_TwoWay-kang_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<section id="solution" class="level3">
<h3 class="anchored" data-anchor-id="solution">Solution</h3>
<p>he First plot: The distribution between groups in terms of spread is not very different and we have roughly a symmetric distribution for all groups and roughly same variance. There is a big difference in ml size between male and female in MFF group, but there is not a big different between between two sex in MG and MFM group. It seems there is an interaction between sex and in mff species group.</p>
</section>
</section>
<section id="p-do-the-plots-above-suggest-there-is-an-interaction" class="level2">
<h2 class="anchored" data-anchor-id="p-do-the-plots-above-suggest-there-is-an-interaction"><strong>(1 p)</strong> Do the plots above suggest there is an interaction?</h2>
<p>Do the lines for each group seem to be very different from parallel?</p>
<section id="solution-1" class="level3">
<h3 class="anchored" data-anchor-id="solution-1">Solution</h3>
<p>[answer]</p>
<p>yes it seems there is an interaction between sex and in mff species group.</p>
</section>
</section>
<section id="fit-the-two-way-interaction-model" class="level2">
<h2 class="anchored" data-anchor-id="fit-the-two-way-interaction-model">Fit the two-way interaction model</h2>
<section id="solution-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-2">Solution</h3>
<p>[answer]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>lm_ml_x_s_xs <span class="ot">&lt;-</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    ml <span class="sc">~</span> sex <span class="sc">+</span> species <span class="sc">+</span> sex<span class="sc">:</span>species</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  , <span class="at">data =</span> dat_kang</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  , <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">sex =</span> contr.sum, <span class="at">species =</span> contr.sum)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
</section>
</section>
<section id="p-check-model-assumptions-for-full-model" class="level2">
<h2 class="anchored" data-anchor-id="p-check-model-assumptions-for-full-model"><strong>(1 p)</strong> Check model assumptions for full model</h2>
<p>Recall that we assume that the full model is correct before we perform model reduction by backward selection.</p>
<section id="solution-3" class="level3">
<h3 class="anchored" data-anchor-id="solution-3">Solution</h3>
<p>[answer]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot diagnostics</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">e_plot_lm_diagostics</span>(lm_ml_x_s_xs)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_10_Exp_TwoWay-kang_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_10_Exp_TwoWay-kang_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.08179149, Df = 1, p = 0.77488</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_10_Exp_TwoWay-kang_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in e_plot_lm_diagostics(lm_ml_x_s_xs): Note: Collinearity plot
unreliable for predictors that also have interactions in the model.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_10_Exp_TwoWay-kang_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid" width="960"></p>
</div>
<div class="cell-output-display">
<p><img src="ADA2_CL_10_Exp_TwoWay-kang_files/figure-html/unnamed-chunk-4-5.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>The residuals are roughly distributed normal based on QQplot. there are no significant outlier. the distribution of data in male group is wider in compare to female but the this difference is not big. There is not enough evidence that we can tell variance is not constant between all groups. based on box-cox plot we do not need transformation. in residuals vs index we can see an structure, because the data have been sorted by sex and species so this is not interpretable. the assumptions are met.</p>
</section>
</section>
<section id="p-anova-table-test-for-interaction-and-main-effects" class="level2">
<h2 class="anchored" data-anchor-id="p-anova-table-test-for-interaction-and-main-effects"><strong>(3 p)</strong> ANOVA table, test for interaction and main effects</h2>
<p>Test for the presence of interaction between sex and species. Also test for the presence of main effects, effects due to the sex and species.</p>
<section id="solution-4" class="level3">
<h3 class="anchored" data-anchor-id="solution-4">Solution</h3>
<p>[answer]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(lm_ml_x_s_xs, <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: ml
               Sum Sq  Df    F value    Pr(&gt;F)    
(Intercept) 210457347   1 11207.3465 &lt; 2.2e-16 ***
sex            232267   1    12.3688 0.0006019 ***
species         37881   2     1.0086 0.3675604    
sex:species    167853   2     4.4693 0.0132688 *  
Residuals     2441207 130                         
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The interaction between sex and species is significant based on 95% confidence Interval.</p>
</section>
</section>
<section id="p-reduce-to-final-model-test-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="p-reduce-to-final-model-test-assumptions"><strong>(1 p)</strong> Reduce to final model, test assumptions</h2>
<p>If the model can be simplified (because interaction is not significant), then refit the model with only the main effects. Test whether the main effects are significant, reduce further if sensible. Test model assumptions of your final model.</p>
<section id="solution-5" class="level3">
<h3 class="anchored" data-anchor-id="solution-5">Solution</h3>
<p>[answer] The full model is final model because the interaction is significant and the assumptions are met.</p>
</section>
</section>
<section id="p-summarize-the-differences" class="level2">
<h2 class="anchored" data-anchor-id="p-summarize-the-differences"><strong>(2 p)</strong> Summarize the differences</h2>
<p>Summarize differences, if any, in sexes and species using relevant multiple comparisons. Give clear interpretations of any significant effects.</p>
<p><em>This code is here to get you started. Determine which comparisons you plan to make and modify the appropriate code. Make the code chunk active by moving the <code>{R}</code> to the end of the initial code chunk line.</em></p>
<pre><code>{R}
library(emmeans)
# Contrasts to perform pairwise comparisons
cont_kang &lt;- emmeans(lm_object, specs = "sex")
cont_kang &lt;- emmeans(lm_object, specs = "species")
cont_kang &lt;- emmeans(lm_object, specs = "sex", by = c("species"))
cont_kang &lt;- emmeans(lm_object, specs = "species", by = c("sex"))
# Means and CIs
confint(cont_kang, adjust = "bonferroni")
# Pairwise comparisons
cont_kang %&gt;% pairs(adjust = "bonf")   # adjust = "tukey" is default</code></pre>
<p><strong>EMM plot interpretation</strong></p>
<p>This <strong>EMM plot (Estimated Marginal Means, aka Least-Squares Means)</strong> is only available when conditioning on one variable. The <strong>blue bars</strong> are confidence intervals for the EMMs; don’t ever use confidence intervals for EMMs to perform comparisons – they can be very misleading. The <strong>red arrows</strong> are for the comparisons among means; the degree to which the “comparison arrows” overlap reflects as much as possible the significance of the comparison of the two estimates. If an arrow from one mean overlaps an arrow from another group, the difference is not significant, based on the adjust setting (which defaults to “tukey”).</p>
<pre><code>{R, fig.height = 5, fig.width = 6}
# Plot means and contrasts
p &lt;- plot(cont_kang, comparisons = TRUE, adjust = "bonf")
p &lt;- p + labs(title = "Bonferroni-adjusted contrasts")
p &lt;- p + theme_bw()
print(p)</code></pre>
<p>Please refer to the Chapter 5 section named <strong><code>emmeans</code> and Bonferroni corrections</strong> for how to appropriately calculate the Bonferroni p-values for a two-way interaction model.</p>
<section id="solution-6" class="level3">
<h3 class="anchored" data-anchor-id="solution-6">Solution</h3>
<p>[answer]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Contrasts to perform pairwise comparisons</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>cont_kang <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(lm_ml_x_s_xs, <span class="at">specs =</span> <span class="st">"sex"</span>, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"species"</span>))</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Means and CIs</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>cont_kang</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>species = Mg:
 sex emmean   SE  df lower.CL upper.CL
 M     1266 28.6 130     1210     1323
 F     1249 27.4 130     1195     1303

species = Mfm:
 sex emmean   SE  df lower.CL upper.CL
 M     1254 29.9 130     1195     1313
 F     1205 27.4 130     1151     1259

species = Mff:
 sex emmean   SE  df lower.CL upper.CL
 M     1362 32.3 130     1298     1426
 F     1178 28.0 130     1123     1234

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>cont_kang <span class="sc">%&gt;%</span> <span class="fu">pairs</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>species = Mg:
 contrast estimate   SE  df t.ratio p.value
 M - F        17.4 39.6 130   0.440  0.6607

species = Mfm:
 contrast estimate   SE  df t.ratio p.value
 M - F        48.8 40.6 130   1.204  0.2307

species = Mff:
 contrast estimate   SE  df t.ratio p.value
 M - F       183.4 42.7 130   4.292  &lt;.0001</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot means and contrasts</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">plot</span>(cont_kang, <span class="at">comparisons =</span> <span class="cn">TRUE</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Tukey-adjusted contrasts"</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">theme_bw</span>()</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_10_Exp_TwoWay-kang_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p><strong>EMM plot interpretation</strong></p>
<p>This <strong>EMM plot (Estimated Marginal Means, aka Least-Squares Means)</strong> is only available when conditioning on one variable. The <strong>blue bars</strong> are confidence intervals for the EMMs; don’t ever use confidence intervals for EMMs to perform comparisons – they can be very misleading. The <strong>red arrows</strong> are for the comparisons among means; the degree to which the “comparison arrows” overlap reflects as much as possible the significance of the comparison of the two estimates. If an arrow from one mean overlaps an arrow from another group, the difference is not significant, based on the adjust setting (which defaults to “tukey”).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>cont_kang <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(lm_ml_x_s_xs, <span class="at">specs =</span> <span class="st">"species"</span>, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"sex"</span>))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Means and CIs</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>cont_kang</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sex = M:
 species emmean   SE  df lower.CL upper.CL
 Mg        1266 28.6 130     1210     1323
 Mfm       1254 29.9 130     1195     1313
 Mff       1362 32.3 130     1298     1426

sex = F:
 species emmean   SE  df lower.CL upper.CL
 Mg        1249 27.4 130     1195     1303
 Mfm       1205 27.4 130     1151     1259
 Mff       1178 28.0 130     1123     1234

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>cont_kang <span class="sc">%&gt;%</span> <span class="fu">pairs</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sex = M:
 contrast  estimate   SE  df t.ratio p.value
 Mg - Mfm      12.2 41.4 130   0.295  0.9531
 Mg - Mff     -95.6 43.1 130  -2.216  0.0722
 Mfm - Mff   -107.8 44.0 130  -2.449  0.0412

sex = F:
 contrast  estimate   SE  df t.ratio p.value
 Mg - Mfm      43.6 38.8 130   1.126  0.4999
 Mg - Mff      70.4 39.2 130   1.797  0.1745
 Mfm - Mff     26.7 39.2 130   0.683  0.7739

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot means and contrasts</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">plot</span>(cont_kang, <span class="at">comparisons =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Tukey-adjusted contrasts"</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">theme_bw</span>()</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="ADA2_CL_10_Exp_TwoWay-kang_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="576"></p>
</div>
</div>
</section>
<section id="solution-7" class="level3">
<h3 class="anchored" data-anchor-id="solution-7">Solution</h3>
<p>[answer]</p>
<p>There are significant size differences (183.4 units in average) between male and female in mff species. also in male group there is significant difference (107.8 units in average) between mfm and mff species, but there is no significant in females.</p>
</section>
</section>
<section id="p-summarize-the-results-in-a-few-sentences" class="level2">
<h2 class="anchored" data-anchor-id="p-summarize-the-results-in-a-few-sentences"><strong>(1 p)</strong> Summarize the results in a few sentences</h2>
<section id="solution-8" class="level3">
<h3 class="anchored" data-anchor-id="solution-8">Solution</h3>
<p>[answer] we analized the data to see What effect does sex and species have on the mandible length of a kangaroo skull. we fit a two way anova model and base on the model the interaction was significant. all the model assumptions were met. There are significant size differences between male and female in mff species. also in male group there is significant difference between mfm and mff species.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>